version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "/ui"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/src/main/resources/polyfill"
  schedule:
    interval: "weekly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
