[build]
image = "ghcr.io/making/ssr-react-spring-boot-graalvm-js"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.http_checks]]
port = 8080
interval = 5000
grace_period = "5s"
method = "get"
path = "/readyz"
protocol = "http"
timeout = 5000

[metrics]
port = 8080
path = "/actuator/prometheus"

[env]
"spring.application.name" = "${FLY_APP_NAME}"